### ISSUE TITLE
Asymmetrical treatment of '+' in Object.toQueryString() and Object.fromQueryString()

### ISSUE THREAD

**Issue by onlyurei** [andrewplummer/Sugar#483] opened 2015-02-02 22:03 UTC
```Object.fromQueryString('foo=bar&broken=wear+a')``` -> {"foo":"bar","broken":"wear+a"}
```Object.toQueryString({"foo":"bar","broken":"wear a"})``` -> "foo=bar&broken=wear+a"

```Object.fromQueryString(Object.toQueryString({"foo":"bar","broken":"wear a"}))``` -> {foo: "bar", broken: "wear+a"} != {"foo":"bar","broken":"wear a"}

In some of my use cases of sugar, a form class has difficulty in initializing properly from its serialized URL due to this asymmetrical treatment of converting space to '+' in ```toQueryString```, but not '+' to space in ```fromQueryString```.

**Comment by andrewplummer** [comment] 2015-02-03 01:41
Duplicate of #457

**Closed by andrewplummer** 2015-02-03 01:41 UTC
