### ISSUE TITLE
Sugar.js won't work with Rhino v1.6

### ISSUE THREAD

**Issue by beders** [andrewplummer/Sugar#447] opened 2014-08-01 02:01 UTC
(tested with the Rhino version that comes with Java 1.6)
Rhino is on 1.5 EcmaScript compatibility level and when I try to eval latest sugar.dev.js I get:
Caused by: javax.script.ScriptException: sun.org.mozilla.javascript.internal.EcmaError: TypeError: Cannot read property "every" from undefined (<Unknown source>#107) in <Unknown source> at line number 107

Caused by 
    alias(array, 'all', 'every');

Not sure how to fix that.

If I use sugar.min.js, I get this:
javax.script.ScriptException: sun.org.mozilla.javascript.internal.EvaluatorException: illegal character (<Unknown source>#18) in <Unknown source> at line number 18

Not sure what illegal is with this line:
function Qa(a,b){function c(a,c){if(a||-1<b.indexOf(c))d+=c}var d="";b=b||"";c(a.multiline,"m");c(a.ignoreCase,"i");c(a.global,"g");c(a.u,"y");return d}function Ra(a){z(a)||(a=s(a));return a.replace(/([\/\'*+?|()[]{}.^$])/g,"\$1")}function U(a,b){return a["get"+(a._utc?"UTC":"")+b]()}function Sa(a,b,c){return a["set"+(a._utc&&"ISOWeek"!=b?"UTC":"")+b](c)}

Any chance sugar.js can be made compatible with 1.5?

**Comment by andrewplummer** [comment] 2015-10-12 18:20
Hi... looks like I finally got around to this. Really sorry for taking so long!

So I had a look at Rhino 1.7, first because that's about how freaking long I've taken to address this issue, and also because it appears that the [archive page](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Downloads_archive) is down. I've managed to hook up the unit tests so if you have links to 1.5 or 1.6 binaries I will take a look. However it looks like 1.7 has a number of issues.

First and most severely, Rhino appears for some reason to mask the `global` object, which wreaks all kinds of havoc (Sinon for example won't even load for this reason alone). I've set up a check for this that seems to work so basic functionality at least can be supporter.

However it also appears that Rhino does not support the `setTimeout` method, which makes about half of the function package useless. This will simply have to be something that Rhino users will have to watch out for.

Additionally there are two other small quirks. One is `Object(str)` on a string results in an object of type "object" but without any keys, so results get strange when treating them as objects. Additionally calling `new Date(d)` on a date object will truncate the milliseconds, which appears to be a bug. I put in a fix by using `new Date(d.getTime())` instead, so at least this one can be fixed.

Note that the new version is 2.0.0 so I'm testing against that (lots has changed).

Thank you for this and for your patience!

**Comment by andrewplummer** [comment] 2015-11-25 14:07
Just an FYI I found the 1.5 and 1.6 binaries, but they won't load as they incorrectly report that the keyword "static" cannot be used. This is true for variable names, but not for object properties, which is the case with Sugar. So it looks like Sugar will implicitly support 1.7 (partially) onward.

**Comment by andrewplummer** [comment] 2016-12-04 15:04
Ok closing this one now. I've confirmed the that the latest version of Rhino works with Sugar, with a side note about the minor quirks listed above.

**Closed by andrewplummer** 2016-12-04 15:04 UTC
Labels: 1.5, Bug, Feature
