### ISSUE TITLE
Support Date.create with a given date context

### ISSUE THREAD

**Issue by tomzx** [andrewplummer/Sugar#499] opened 2015-05-23 17:05 UTC
Hi,

I'd like to be able to use fuzzy date on an existing date/context (instead of the current Date), something like the following:

```
var someDate = new Date(2010, 01, 05);
Date.create('next monday', someDate);
```

My current use case is as such: I want to be able to parse many datetime representation that are given to me as strings. However, if someone says "now", I want the "now" value to be exactly the same for every representation.

```
var output = [];
var now = new Date();
for (var i in queries) {
    output.push(Date.create(queries[i], now));
}
```

As such, I would create a single instance of a Date which I'd reuse when calling Date.create so that it can do things relative to this Date instead of the current date.

**Comment by andrewplummer** [comment] 2015-07-13 16:01
I don't really understand your example (isn't `now` in the example the current date anyway? As such it wouldn't make a difference if you passed it in or not), but I definitely get the use case.

The problem is that (I'm sure you get this but just to spell it out) the fuzzy date "next monday" is relative, and the code deciding what it is relative to is currently unreachable. This has actually been addressed in the next version of Sugar, and there will be a way to override the internal `getNewDate` so that you can make dates relative to something other than the current date.

However the use case you want seems like it might warrant an even simpler pattern. As always though, this is mostly an issue of overloading arguments. Currently the 2nd argument to create is the locale code, and I think it needs to stay that way.

What if we could have an instance method like so:
```
var d = new Date(2010, 01, 05);
d.create('next monday');
```
The instance method would be identical to `Date.create` except that the instance itself will be the base for any relative dates instead of the current date?

**Comment by tomzx** [comment] 2015-07-13 23:06
@andrewplummer That would work. I was trying to keep the same `Date.create` syntax, but there's obviously no reason to support something better :)

Let me know what I could do to get this feature started.

Note: For the example, what I was attempting to say was that if I run something such as

````
var output = [];
var now = new Date();
for (var i in queries) {
	output.push(Date.create(queries[i], now));
	// lots of stuff taking an awful amount of time to process
}
```

any `Date.create` call would be relative to the initially given date. Thus, all dates pushed in the output array would be relative to the time I started the loop.

**Comment by andrewplummer** [comment] 2015-07-14 03:01
Ok gotcha now. Actually this feature would I think be quite trivial to implement, so let me have a look!

**Comment by andrewplummer** [comment] 2015-08-04 16:11
OK, for various reasons I've decided to implement this as `Date#get`. So what you were trying to with this:

```
var someDate = new Date(2010, 01, 05);
Date.create('next monday', someDate);
```

will now be:

```
var someDate = new Date(2010, 01, 05);
someDate.get('next monday');
```

This will go out with the next version!

**Comment by tomzx** [comment] 2015-08-04 16:21
Awesome! I'll give it a try as soon as I have some free time.

**Comment by tomzx** [comment] 2015-08-04 22:53
I just tested c65c23333646bd8355f7d65c11fd8b1b9d86b103 and it works very well for me.

Thanks!

**Comment by andrewplummer** [comment] 2015-08-06 16:44
Great! Going to keep this open for now until final release!

**Closed** 2016-11-24 12:45 UTC
Labels: Feature
