### ISSUE TITLE
.lock method for functions

### ISSUE THREAD

**Issue by Alexsey** [andrewplummer/Sugar#451] opened 2014-08-08 18:40 UTC
<code>.lock</code> method acts like <code>.fill</code>, but result function ignores any further arguments. As <code>.fill</code> it except <code>undefined</code> as placeholders for limited numbers of arguments which would not be ignored.

Use cases, where <code>.lock</code> is more handsome than <code>.fill</code>:
- lets log '!' 10 times

```
(10).times(console.log.lock('!'));
```

or almost always when we are passing function with non-limited arguments quantity
- passing non-js functions. For example NodeJs's native functions which will not work with extra arguments

```
async.auto({
  file: fs.readFile.lock('data.txt', 'utf-8', undefined)
}, callback);
```

(this example is based on example from <code>async</code> documentation, as one which will not work without nesting functions because of extra arguments)
- 'overloaded' function with different behavior based on number of arguments. Only with <code>.lock</code> we could pass it wherever we want with confidence that it will work as we expect, no matter which extra arguments would be passed to it.

alternate to name <code>lock</code> could be <code>close</code> or <code>shut</code>.

**Comment by andrewplummer** [comment] 2015-09-14 09:10
First, very sorry for the major delay in responding.

I've read through this feature but I'm still a bit confused about both the functionality and the use case.

First, is this function running every time but simply locking the arguments? Or is it essentially memoizing and always returning the same value?

If it's the first case, then I'm also rather confused about the use case where a function would be called with an unknown number of arguments. Why would you not have an idea about what would be passed into `readFile` in the second example?

**Comment by Alexsey** [comment] 2015-09-14 09:59
simple implementation would looks like this

```
function lock (f) {
  var lockedArgs = [].slice.call(arguments, 1)
  return function () {
    var freeArgs = [].slice.call(arguments)
    var i = 0
    var args = lockedArgs.map(function (v) {return v === undefined ? freeArgs[i++] : v})
    return f.apply(this, args)
  }
}
```

About second example - I know what arguments would be - it would be callback and empty object. Problem is that <code>fs.readFile</code> will fall if you pass four arguments in it. Here is a <a href="https://github.com/caolan/async#auto">link</a> on this case

There is also possibility for curring, but I'm not sure about it (do not call <code>f</code> until all <code>undefined</code> arguments are filled but returning new function with less and less unfilled arguments)

Also about placeholder <code>undefined</code> - it should be consistent with <code>.fill</code> but for now, when <code>lodash</code> takes just <code>_</code> for it, I think in <code>Sugar</code> we also need to have some nice looking alternative. But may be it should be a separate issue

**Comment by andrewplummer** [comment] 2015-09-14 10:26
Hm... I see what you're saying now, but...

Sugar is always difficult to balance. Commonly I have to question how common the use case is balanced against how difficult it would be to do the same thing in plain JS.

In this case it seems the use case is needing a function that curries arguments, but not knowing ahead of time how many arguments will be passed in. It seems to me that it would be fairly rare to not know ahead of time how many arguments your function will be called with.

To balance against that is what the plain JS:

```
function read (cb) {
  fs.readFile.lock('data.txt', 'utf-8', cb);
}
async.auto({
  file: read // etc
});
```

The plain JS is very straightforward and easy to read. It's not so much harder to write either. To me it doesn't seem to outweigh the use case here.

But maybe I'm wrong? Is it so common to have function that will be called with more arguments than expected so that you need to lock it?

**Comment by Alexsey** [comment] 2015-09-14 11:40
Well from time to time I would use this if it where in lib. But since I post it a year ago <code>lodash</code> 3.x has been introduced and it has <code><a href="https://lodash.com/docs#ary">.ary</a><code> function which is handling same problem but from some different angle: <code>.fill</code> is almost <code>.fill</code> + <code>.ary</code>. Also <code><a href="https://lodash.com/docs#curry">.curry</a></code> could suit those. If you have planes for any of thous - custom <code>.lock</code> would be surplus. But if not - you could cover some use cases with <code>.lock<code>.

**Comment by Alexsey** [comment] 2015-09-14 11:49
@jdalton, the author of <code>lodash</code> now is extra preciseness about what to add to library so if <code>.ary</code> where introduced - this means that there are use cases for that

P.S. I do not in any way suggest to copy <code>lodash</code>. Just use their experience

**Comment by vendethiel** [comment] 2015-09-14 12:29
Also your implementation needs to capture the `this` in the function itself and use it in the closure (for `f.apply`)

**Comment by Alexsey** [comment] 2015-09-14 12:33
If your need to capture <code>this</code> - use <code>.bind</code>. Usually it is not impotent

**Comment by andrewplummer** [comment] 2015-09-15 06:12
hmm... lodash seems to be doing a lot here. `.curry` is very interesting and does something not possible in Sugar now (might be interested in adding, but different thread I guess), but it doesn't seem like it would work for `lock` as it continues to curry any arguments passed, even if the `arity` parameter is passed (it does not ignore arguments).

`ary` is also interesting but I find the naming horrible. The example with "parseInt" is something that's come up before, but I'm not sure it couldn't be accomplished with existing methods. For example if Sugar were to implement `ary`:

```
['6', '8', '10'].map(parseInt.ary(1));
```

That's nice and clean, but:

```
['6', '8', '10'].map(parseInt.fill(undefined, 10));
```

This isn't bad either. In fact, in this case I think it gets plus points for being more explicit and also because there are some environments (obsolete now of course, but still) that will error if the radix is not passed to `parseInt`, so better to "fill" it.

Your original example of `fs.readFile` is much better. To summarize that one:

```
var files = ['file1.txt', 'file2.txt', 'file3.txt'];
function done() { // ... }
files.forEach(fs.readFile.fill(undefined, 'utf-8', done));
```

The problem is that this won't work because `readFile` is checking for the *last* argument. `forEach` will pass 3 arguments into the filled function. The first argument will take the place of `undefined`, but the other 2 (array index and the array itself) will be added to the end of the arguments because this is how `fill` works. The only way around this is to create a function as in my second comment.

It seems that if Sugar decides to support this there are a few possible ways to do it:

1. Sugar introduces an `ary`-like method. This method can lock the number of arguments like this:

```
files.map(fs.readFile.ary().fill(undefined, 'utf-8', done));
```

Notice that in this example `ary` MUST come before `fill`, not after. The reason is that even if `ary` locks the filled function to 3 arguments, it is inside that the filled function that the 3 passed arguments are added to the curried arguments, so the result will be the same as not using `ary`.

2. Your idea. `.lock()` acts as `.fill()`, but does not concatenate arguments.

```
files.map(fs.readFile.lock(undefined, 'utf-8', done));
```

3. `fill()` could change to accept arguments as an array instead of enumerated on the method itself. This would free up method arguments so that other parameters can be passed:

```
files.map(fs.readFile.fill([undefined, 'utf-8', done], true)); // "true" to tell the function to lock the arguments
```

4. ???

**Comment by Alexsey** [comment] 2015-09-15 12:38
Yes, <code>.curry</code> will not help is <code>lodash</code> realization. I thought it work different when second argument is set. 

About name <code>.ary</code> - agree with you - it is definitely not the best. BTW in can be used as before <code>.fill</code>
<code>files.map(fs.readFile.ary(3).fill(undefined, 'utf-8', done));<code>
as after
<code>files.map(fs.readFile.fill(undefined, 'utf-8', done).ary(1));<code>

Force <code>.fill</code> to always accept binded arguments in array is definitely a bad idea

I think add something like <code>.ary</code> but may be with different name is the best option because as far as <code>.lock</code> is <code>.fill</code> + <code>.ary</code> this will separate responsibilities

**Comment by andrewplummer** [comment] 2015-09-15 13:16
Okay... I generally like your idea. The only problem I have now is that the behavior between `fill` and `partial` seems slightly different so that if we just add `ary` it will only allow `.ary` + `.fill`,  `.fill` + `.ary` will not work. This is (I think) because `fill` will keep adding arguments to the end of a function, but `partial` does not behave this way. So even if `ary` cuts off the arguments, the ones that do get in will be appended so the filled function will be called with more than defined in `ary`. I'll look deeper into this later and try to make sure this is why.

For now, what do you think about this:

I would like to bring `fill` functionality in line with Lodash/Underscore `partial` and possibly rename the method to match. I feel now that this method is well enough understood that the naming is expected and reasonably descriptive. `ary` on the other hand is not. What do you think about your suggestion `lock` instead of `ary`?

**Comment by Alexsey** [comment] 2015-09-15 13:24
<code>lock</code> is a name instead of <code>ary</code> with <code>.ary</code> functionality or <code>.lock</code> as function instead of <code>.ary</code>?

**Comment by andrewplummer** [comment] 2015-09-15 13:33
I meant a different name for `ary` with `ary` functionality.

**Comment by Alexsey** [comment] 2015-09-15 13:56
<code>lock</code> is a good. Also we could consider about <code>rank</code> which is better related to single numeric argument

**Comment by jdalton** [comment] 2015-09-15 14:26
Just for background info `ary` comes from [n-ary](https://en.wikipedia.org/wiki/Arity#n-ary).

**Comment by andrewplummer** [comment] 2015-09-15 16:24
Okay, this is a bit tangential but I just spent some time bringing `fill` in line with `partial`, and I'm heavily leaning to changing the name for the 2.0.0 release to be in line with lodash/underscore (and of course others as well). This doesn't directly decide what to do with `ary` however. @Alexsey I'm still considering your original idea that `lock` could be essentially the same as partial but simply doesn't go on to further curry overloaded arguments (thereby essentially "locking").

As for the naming, both `ary` and `rank` are extremely precise terms (wasn't familiar of "rank" but looking into it seems exactly right) and I can definitely see the reason for choosing either of these. However I don't think it's a stretch to say that both of these terms suffer somewhat for being so precise and are rather unfamiliar to most people. I think "clarity" in naming is a balancing act and familiarity with a term is part of what makes it clear. Sugar has in a number of cases opted for more generalized terms over more precise ones -- sometimes to its detriment (believe me the irony isn't lost about going *back* to `partial` ... a similar discussion is also happening about `assign` vs. `format` for strings). In this case though, I think `lock` does a much better job of conveying it's purpose, so definitely leaning toward it.

**Comment by jdalton** [comment] 2015-09-15 16:32
Do you have any reading material for `lock`? I'm just popping in to the thread because of a @ mention. So I don't have a ton of context.

**Comment by andrewplummer** [comment] 2015-09-15 16:39
Thanks for stopping by :)

erm... no reading material per-se ... it's just a proposal at this point. @Alexsey was the first one to propose, so everything is in this thread I think.

**Comment by andrewplummer** [comment] 2015-11-20 18:57
Ok, as discussed `lock` will be Sugar's equivalent to `ary`. It simply locks the function so that no further arguments are accepted. I see this as preferable to the original request as 1) `lock` doesn't convey any sense of currying arguments, but does quite well convey the sense of what `ary` does and 2) Having the ability to lock arguments is applicable to more than just partial functions.

I have also gone out of the way to make `lock` play nicely with `partial` as it's very difficult to understand how they work together otherwise. Essentially, `partial` itself is also endowed with the ability to truncate arguments based on a flag. Instead of creating a new function, calling `lock` on a partial function will simply set this flag. This means you can do this:

```
files.map(fs.readFile.partial(undefined, 'utf-8', done).lock());
```

And it will just work. `lock(n)` will always mean "total concatenated arguments at execution time", which is much more intuitive than having to perform math for partial functions.

**Comment by andrewplummer** [comment] 2016-12-04 14:59
This is released now so closing!

**Closed by andrewplummer** 2016-12-04 14:59 UTC
Labels: Feature
