### ISSUE TITLE
Daylight Savings Time on iOS not supported

### ISSUE THREAD

**Issue by shaunetobias** [andrewplummer/Sugar#470] opened 2014-10-29 15:46 UTC
To generate an array of all times in 15 minute increments, I placed the following in a loop:

thisTime = (15).minutesAfter(thisTime);

When the loop got to Sunday morning (when my local clocks go back), the array would then display:

01:00, 01:15, 01:30, 01:45, 01:00, 01:15, 01:30, 01:45, 01:00, 01:15, 01:30, 01:45, 01:00, 01:15, 01:30, 01:45, 01:00, 01:15, 01:30, 01:45, 01:00, 01:15, 01:30, 01:45,  (until end of loop).

All times are in UTC.

I changed to plain ol' JS and it fixed it:

thisTime = Date.create(thisTime.getTime() + 15 * 60000);

returns the correct times:

01:00, 01:15, 01:30, 01:45, 01:00, 01:15, 01:30, 01:45, 02:00, 02:15, 02:30, 02:45, 03:00, 03:15, 03:30, 03:45 (until end of loop)

**Comment by andrewplummer** [comment] 2015-09-14 07:22
Really sorry about how long this has taken to address. To be clear, are you saying that in the Sugar method it went into an infinite loop?

**Comment by andrewplummer** [comment] 2015-09-14 07:26
This is almost certainly a duplicate of #468 so I'm going to close this one out and will have a look! Thank you.

**Closed by andrewplummer** 2015-09-14 07:26 UTC
Labels: Bug
