### ISSUE TITLE
korean parsing seems to fail when whitespaces are present

### ISSUE THREAD

**Issue by deddu** [andrewplummer/Sugar#532] opened 2016-01-12 21:24 UTC
Hi Andrew, I am having the following issue 
```
Date.create('2016년 5월 12일', 'ko')
Invalid Date
Date.create('2016년5월12일', 'ko')
Thu May 12 2016 00:00:00 GMT-0500 (CDT)
```
The problem arises when using Intl.dateTimeFormat in chrome and firefox for korean, as those localizations include the whitespaces. I would be glad to submit a Pull Request, but I am a tad confused about how the locale files work. Do you have any pointer for me? Thanks. And.. AWESOME library!! Date.create is the exact api I was dreaming. gorgeous.

**Comment by andrewplummer** [comment] 2016-01-12 21:30
This should be a duplicate of #524, so going to close this. Will go out soon!

**Closed by andrewplummer** 2016-01-12 21:30 UTC

**Comment by deddu** [comment] 2016-01-12 21:34
I had missed [the commit](https://github.com/andrewplummer/Sugar/commit/c69fa1108dc9bafec4d4cd80d09791082a4f7dbd). You rock.
