### ISSUE TITLE
date.format('{yy}') rounds 2001 to 1

### ISSUE THREAD

**Issue by voxmatt** [andrewplummer/Sugar#521] opened 2015-11-17 19:33 UTC
date.js line 36
```
'yy': function(d) {
      return callDateGet(d, 'FullYear') % 100;
},
```
results in 2001 -> 1 when '01' is the desired output

**Comment by andrewplummer** [comment] 2015-11-18 15:29
Thanks for this! This one is a duplicate of #498. Sat on it for a while but it's fixed now and should go out soon!

**Closed by andrewplummer** 2015-11-18 15:29 UTC
